# Generated by Django 3.2.10 on 2022-01-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperQuestion',
            new_name='Patient',
        ),
    ]
