# Generated by Django 3.2.10 on 2022-01-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0002_rename_superquestion_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='que_rico_mami',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='question_text',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
