# Generated by Django 3.2.10 on 2022-01-09 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0003_auto_20220109_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='register date'),
            preserve_default=False,
        ),
    ]
