# Generated by Django 3.2.10 on 2022-01-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0004_auto_20220109_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='arduino_id',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
