# Generated by Django 3.2.10 on 2022-01-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0007_auto_20220109_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arduino_id', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='arduino',
            name='votes',
        ),
    ]
