# Generated by Django 3.2.10 on 2022-01-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0008_auto_20220109_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arduinolog',
            name='arduino_id',
        ),
        migrations.AddField(
            model_name='arduinolog',
            name='patient',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
