# Generated by Django 3.2.10 on 2022-01-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0009_auto_20220109_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduino',
            name='spo2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
