# Generated by Django 3.2.10 on 2022-01-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0010_arduino_spo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduino',
            name='spo2',
            field=models.CharField(max_length=12),
        ),
    ]
