# Generated by Django 3.2.10 on 2022-01-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0011_alter_arduino_spo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arduino',
            name='spo2',
        ),
        migrations.AddField(
            model_name='arduinolog',
            name='spo2',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
