# Generated by Django 3.1.6 on 2022-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0013_arduinolog_heart_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArduinoLog',
        ),
        migrations.AlterField(
            model_name='arduino',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
