# Generated by Django 3.1.6 on 2022-01-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0015_arduinolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduino',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='arduino_check.patient'),
            preserve_default=False,
        ),
    ]
