# Generated by Django 3.1.6 on 2022-01-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0016_arduino_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='arduino_id',
        ),
    ]
