# Generated by Django 3.1.6 on 2022-01-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0017_remove_patient_arduino_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinolog',
            name='spo2',
            field=models.FloatField(max_length=12),
        ),
    ]
