# Generated by Django 3.1.6 on 2022-01-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_check', '0018_auto_20220113_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinolog',
            name='heart_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arduinolog',
            name='spo2',
            field=models.FloatField(),
        ),
    ]
